#!/bin/bash

##
# takes a look at all new packages in our temp dir
# moves them into our repo dir
# updates repo.db
# cleans up build dir
##
# written by Tim 'bastelfreak' Meusel'
##

TMPDIR="/var/lib/jenkins/packages"
FINALDIR="/var/www/archlinux/aur/os/x86_64"
BUILDDIR="/mnt/aur/build_test"
if [ "$(whoami)" != "jenkins" ]; then
  echo "only execute this as user jenkins"
  exit 1
fi

cd "${TMPDIR}" || exit 1
while read -r package; do
  pkgfile="$(basename "${package}")"
  mv "$package" "${FINALDIR}/"
  repo-add --remove "${FINALDIR}/aur.db.tar.gz" "${FINALDIR}/${pkgfile}"
  echo "added ${package}"
  # clean up if jenkins provided us the package name
  if [ -n "$1" ]; then
    packagebase="$1"
    echo "cleaning up $packagebase"
    # build that installed systemd components have another btrfs subvol
    # this needs to be cleaned up first
    if [ -d "${BUILDDIR}/${packagebase}/var/lib/machines" ]; then
      sudo /usr/bin/btrfs subvolume delete "${BUILDDIR}/${packagebase}/var/lib/machines"
      echo "cleaned up ${BUILDDIR}/${packagebase}/var/lib/machines"
    fi
    # this should be true for all builds, but you never know...
    if [ -d "${BUILDDIR}/${packagebase}" ]; then
      sudo /usr/bin/btrfs subvolume delete "${BUILDDIR}/${packagebase}"
      echo "cleaned up ${BUILDDIR}/${packagebase}"
    fi
  fi
done < <(find "${TMPDIR}" -maxdepth 1 -type f -iname '*.pkg.tar.xz' -o -iname '*.pkg.tar.zst')
